connect('weblogic','weblogic','t3://localhost:7001')
edit()
startEdit()
cd('/SecurityConfiguration/base_domain')
set('CrossDomainSecurityEnabled','true')
set('ExcludedDomainNames',jarray.array([String('81sp4-domain-name'), String('81sp5-domain-name'),String('81sp6-domain-name')], String))
set('Credential','wireless')
save()
activate()
